//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaRepository.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRecord
    {
        public int ID { get; set; }
        public int ServiceCode { get; set; }
        public int ProviderID { get; set; }
        public int MemberID { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateProvided { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool ServiceVerified { get; set; }
        public bool FeeVerified { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
